### ISSUE TITLE
Change Get Slice After Selecting Criterion without starting Debugging Session

### ISSUE THREAD

**Issue by arya23065** [Debugger-Plus-Plus/debuggerpp#24]
User flow - A user selects a slicing criterion, the slice is generated and line is grayed, now the user can put breakpoints on slice lines (non slice line breakpoints are muted/disabled), and pressing Debugger++ button in toolbar starts debugging session.

**Comment by arya23065** [comment]
Post meeting - only have to automatically add a breakpoint to the first slice line

**Comment by LuuO** [comment]
automatically add a breakpoint to the first slice line  - Done in b2cc60c5831e61f0c12df7b333d387dd7790b1ac
