### ISSUE TITLE
Do not open File Explorer when slice produced

### ISSUE THREAD

**Issue by LuuO** [Debugger-Plus-Plus/debuggerpp#34]

**Comment by LuuO** [comment]
Remove this line:
https://github.com/Debugger-Plus-Plus/debuggerpp/blob/9079b24d3cffaaadfd853204b1c182f01c2de824/src/main/kotlin/team57/debuggerpp/execute/DynamicSliceDebuggerRunner.kt#L111

**Comment by arya23065** [comment]
Completed - 1f2dc0af72559b52c424bde739e9da4743f21e8e
